version: '2'
services:
  users-service:
    build: ./users-service
    container_name: users-service
    ports:
    - "8123:8123"
    depends_on:
    - db
    links:
    - db
    environment:
    - DATABASE_HOST=db
  db:
    build: ./test-database
    container_name: db